In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
engine = create_engine('sqlite:///../data/data.sqlite')

In [6]:
csv_data = pd.read_csv('../data/data-clean.csv')
csv_data.head()

,date,state,n_killed,n_injured,participant_age,participant_gender,participant_status,participant_type
0,2013-01-01,Pennsylvania,0,4,0::20,0::Male||1::Male||3::Male||4::Female,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...
1,2013-01-01,California,1,3,0::20,0::Male,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...
2,2013-01-01,Ohio,1,3,0::25||1::31||2::33||3::34||4::33,0::Male||1::Male||2::Male||3::Male||4::Male,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...
3,2013-01-05,Colorado,4,0,0::29||1::33||2::56||3::33,0::Female||1::Male||2::Male||3::Male,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...
4,2013-01-07,North Carolina,2,2,0::18||1::46||2::14||3::47,0::Female||1::Male||2::Male||3::Female,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...